<a href="https://colab.research.google.com/github/Mugund-K/DL_Course/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([1, 2, 3])

In [3]:
X

array([1, 2, 3])

In [4]:
type(X)

numpy.ndarray

In [5]:
l = [ 4, 5, 6 ]
X = np.asarray(l)
type(X)

numpy.ndarray

In [6]:
X.shape

(3,)

In [7]:
print(X)

[4 5 6]


In [8]:
X = np.asarray(l, float)
print(X)

[4. 5. 6.]


In [9]:
X.shape

(3,)

In [10]:
X = np.array([[1,2,3],[4,5,6]])
print(X)

[[1 2 3]
 [4 5 6]]


In [11]:
X.shape

(2, 3)

In [12]:
X[0, 0]

1

In [13]:
X[0, :2]

array([1, 2])

In [14]:
X[0, :]

array([1, 2, 3])

In [15]:
X = np.zeros((4, 5))

In [16]:
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
X = np.eye(4,4)

In [20]:
X

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
X = np.random.random((4,5))

In [22]:
X

array([[0.5301658 , 0.24587974, 0.24757662, 0.72389629, 0.31839919],
       [0.94178106, 0.78158392, 0.90511581, 0.86869037, 0.78689206],
       [0.09441779, 0.61635912, 0.0259153 , 0.70455764, 0.46221388],
       [0.16126543, 0.76201547, 0.29285617, 0.17247407, 0.18386954]])

In [23]:
Z = X.T

In [24]:
Z

array([[0.5301658 , 0.94178106, 0.09441779, 0.16126543],
       [0.24587974, 0.78158392, 0.61635912, 0.76201547],
       [0.24757662, 0.90511581, 0.0259153 , 0.29285617],
       [0.72389629, 0.86869037, 0.70455764, 0.17247407],
       [0.31839919, 0.78689206, 0.46221388, 0.18386954]])

In [25]:
Y = X.reshape(20,1)

In [26]:
Y

array([[0.5301658 ],
       [0.24587974],
       [0.24757662],
       [0.72389629],
       [0.31839919],
       [0.94178106],
       [0.78158392],
       [0.90511581],
       [0.86869037],
       [0.78689206],
       [0.09441779],
       [0.61635912],
       [0.0259153 ],
       [0.70455764],
       [0.46221388],
       [0.16126543],
       [0.76201547],
       [0.29285617],
       [0.17247407],
       [0.18386954]])

In [27]:
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [28]:
B = np.arange(5)
B

array([0, 1, 2, 3, 4])

In [29]:
C = A + B
D = A - B
E = A * B

In [30]:
C

array([0, 2, 4, 6, 8])

In [31]:
D

array([0, 0, 0, 0, 0])

In [32]:
E

array([ 0,  1,  4,  9, 16])

In [33]:
print(A, A+1)

[0 1 2 3 4] [1 2 3 4 5]


In [35]:
A = np.random.random((2,3))
print(A)
print(A+1)

[[0.11597272 0.29100979 0.98951072]
 [0.02744814 0.50126579 0.18971036]]
[[1.11597272 1.29100979 1.98951072]
 [1.02744814 1.50126579 1.18971036]]


In [36]:
A = np.floor(np.random.random((2,3)) * 10)
A

array([[6., 7., 1.],
       [8., 9., 4.]])

In [37]:
u = [1, 2, 3,]
v = [-1, 0, 1]
pl = np.inner(u, v)
print(pl)

2


In [38]:
p2 = np.outer(u, v)
p2

array([[-1,  0,  1],
       [-2,  0,  2],
       [-3,  0,  3]])

In [39]:
A = np.ones((2,3))
B = np.ones((3,2))

np.dot(A, B)

array([[3., 3.],
       [3., 3.]])

In [40]:
np.dot(B.T, A.T)

array([[3., 3.],
       [3., 3.]])

In [41]:
A.sum()

6.0

In [42]:
A.sum( axis = 0)

array([2., 2., 2.])

In [43]:
A.sum( axis = 1)

array([3., 3.])

In [44]:
A.max()

1.0